Repository Loyolazz/CompassFlix, pull requests merged in 2022-09, with the labels that each got.

#43 fix: bug de navegação resolvido
  src/routes/stack/stack.js
  src/screens/seriesDetail/index.js
Labels: enhancement, good first issue, bug resolve

#45 Lists arthur
  package-lock.json
  package.json
  src/Components/ModalExitAccount/index.js
  src/assets/Ciber Security.pdf
  src/assets/javascript.pdf
  src/routes/routes.js
  src/routes/routesProfile/routesProfile.js
  src/routes/routesProfileX/routesProfileX.js
  src/routes/stack/stack.js
  src/screens/ProfileX/index.js
  src/screens/ProfileX/subScreenProfile/MoviesEvaluation/index.js
  src/screens/ProfileX/subScreenProfile/MoviesFavorites/index.js
  src/screens/ProfileX/subScreenProfile/SeriesEvaluation/index.js
  src/screens/ProfileX/subScreenProfile/SeriesFavorites/index.js
  src/screens/login/login.js
  src/screens/movieLists/movieList.js
  src/screens/movieLists/style_movieList.js
  src/screens/moviesDetail/moviesDetail.js
  src/screens/selectionMovies/selectionMovies.js
  src/screens/seriesDetail/index.js
  src/services/api.js
  yarn.lock
Labels: enhancement, bug resolve, FEAT

#49 List arthur estevao
  App.js
  src/Components/seeMovieListComp/index.js
  src/routes/routesProfileX/routesProfileX.js
  src/screens/movieLists/movieList.js
  src/screens/seeMovieList/index.js
  src/screens/selectionMovies/selectionMovies.js
  src/services/api.js
Labels: enhancement, good first issue, FEAT

#53 Merge
  src/Components/ModalAvaluate/style.js
  src/Components/ModalExitAccount/index.js
  src/Components/ModalExitAccount/styles.js
  src/screens/login/style_login.js
  src/screens/movieLists/movieList.js
  src/screens/movieLists/style_movieList.js
  src/screens/moviesDetail/style_moviesDetail.js
  src/screens/seeMovieList/style copy.js
  src/screens/selectionMovies/style_selectionMovies.js
  src/screens/selectionSeries/styles.js
  src/screens/seriesDetail/style.js
Labels: bug resolve, FEAT
